#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = swww-daemon
exec-once = swww img /home/aura/Downloads/wallhaven-e89l7k.jpg
exec-once = waybar
exec-once = swaync
exec-once = blueman-applet
exec-once = cava
exec-once = gsettings set org.gnome.nautilus.preferences click-policy 'single'
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store