preload = /home/aura/Pictures/wallpaper/wall.jpg
preload = /home/aura/Pictures/wallpaper/arrow.jpg

wallpaper = eDP-1,/home/aura/Pictures/wallpaper/wall.jpg
wallpaper = HDMI-A-1,/home/aura/Pictures/wallpaper/arrow.jpg